apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-deplt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/steam-circlet-442814-e1/terraform/result
          name: result-container
          ports:
            - containerPort: 80
              name: result-port
          livenessProbe:
            httpGet:
              path: /
              port: result-port
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 2
            initialDelaySeconds: 5
