apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-deplt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/steam-circlet-442814-e1/terraform/vote
          name: vote-container
          ports:
            - containerPort: 5000
              name: vote-port
          livenessProbe:
            httpGet:
              path: /
              port: vote-port
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 2
            initialDelaySeconds: 5
