apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker-deplt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/steam-circlet-442814-e1/terraform/worker
          name: worker-container
